[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Ops"
  url = "posts/ops/"
  weight = -109

[[main]]
  name="Dev"
  url = "posts/dev/"
  weight = -109

[[main]]
  name="Golang"
  parent="Dev"
  url = "categories/golang"
  weight = -110

[[main]]
  name="Rust"
  parent="Dev"
  url = "categories/rust"
  weight = -109

# [[main]]
#   name="Python"
#   parent="Dev"
#   url = "categories/python"
#   weight = -108


[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/rogerogers"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/itsrogerogers"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
